### ISSUE TITLE
Images gone Blank

### ISSUE THREAD

**Issue by Regnak85** [InventivetalentDev/AnimatedFrames#111] opened 2019-03-06 16:16 UTC
## What steps will reproduce the problem?  
Don't know how to reproduce. 
I make some Pictures, some Animated Frames. Everything worked. 
And then, next time i watched, nothing to see, excempt this:

http://666kb.com/i/e1tszw99yxxxrt35y.jpg

## What were you expecting to happen? What happened instead?  
That the Images were still on the Screen

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.2
## What Spigot version are you using? *Type /version*  
1.13.2
## What plugins are you using? *Type /plugins*  
http://666kb.com/i/e1tt1wpvrobwd13d2.jpg
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nope, No Error shown
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by Th3Shadowbroker** [comment] 2019-03-06 17:16
Hi @Regnak85,
I've tried to reproduce your problem by creating a 4x4 and a 10x9 Frame. I've also tried leaving the view distance and the chunk as well as restarting the server. However the frames were not loaded until I rejoined after the restart. My suspicion is that the problem is related to the PacketListenerAPI. (I'm using 3.7.2). Could you update the `/plugin`-command screenshot? I'm getting a 404.

**Comment by Regnak85** [comment] 2019-03-06 18:52
I am using PacketListenerAPI 3.7.1 ... cant find 3.7.2 ? DevBuild?

Here my Plugins:
https://s17.directupload.net/images/190306/pibnumk6.jpg

**Comment by Th3Shadowbroker** [comment] 2019-03-06 19:40
I build the PacketListenerAPI 3.7.2 from git [PacketListenerAPI_v3.7.2-SNAPSHOT.zip](https://github.com/InventivetalentDev/AnimatedFrames/files/2937921/PacketListenerAPI_v3.7.2-SNAPSHOT.zip) (had to zip the jar because github denies jar-uploads). As I said im not really sure about the origin of the problem you described or if an updated version of the PacketListenerAPI might solve it, especially because there's no error-log. What do you think @InventivetalentDev ?

**Comment by Regnak85** [comment] 2019-03-07 09:21
I could reproduce this. I restarted the Server -> The Images were back.
Then, i left the world, and i was in the End.
No one was in the world with the Pictures.
After a while, i returned to the World -> Every Picture was blank again.
New Server Restart, and Pictures back again. 
So, if the World with the Pictures go unloading, the Pictures seem not to load again, if you re-enter the world.

**Comment by InventivetalentDev** [comment] 2019-03-07 14:48
I'll look into this again.

**Comment by InventivetalentDev** [comment] 2019-03-07 15:35
I still can't seem to reproduce this issue. I tried going to both the Nether and The End and the images reappeared just fine when going back. And I honestly can't figure out how this happens, as the plugin already handles possible unloads caused by e.g. changing worlds...   

How long were you in a different world to get the images to disappear?

**Comment by Manerr** [comment] 2019-04-16 19:55
Exactly the same issue
This has worked and then after disconnection/restart server, nothing more
![jEf4GHa](https://user-images.githubusercontent.com/1338257/56239752-1c6e6780-6092-11e9-843f-fbecff5f5c7e.png)
AnimatedFrames: 4.11.2-SNAPSHOT
MapManager: 1.7.2-SNAPSHOT
PacketListenerAPI: 3.7.2-SNAPSHOT
Server: PaperSpigot 620 (API 1.13.2-R0.1-SNAPSHOT)

**Comment by Drison64** [comment] 2019-04-27 14:55
Hello, i have the same issue,

I think he use 1.13.2 Paper, because me and my friends have the same issue, after some while every frame are blank, it can be fixed only after restart of the server.

**Closed** 2019-07-03 15:39 UTC
Labels: can't reproduce, wontfix
